<template>
  <ion-page><ion-header><ion-toolbar><ion-title>{{ title }}</ion-title><ion-button v-if="mode === 'discover'" slot="end" @click="isAddOpen = true">Add movie</ion-button></ion-toolbar></ion-header><ion-content><main class="page-shell"><ion-searchbar v-if="mode === 'discover'" v-model="query" placeholder="Search movies, genres, directors" /><ion-segment v-if="mode === 'watchlist'" v-model="filter" class="segment"><ion-segment-button value="all">All</ion-segment-button><ion-segment-button value="Not Watched">To watch</ion-segment-button><ion-segment-button value="Watched">Watched</ion-segment-button></ion-segment><div v-if="mode === 'discover'" class="filter-row"><ion-chip v-for="genre in genres" :key="genre" :color="selectedGenre === genre ? 'primary' : undefined" @click="selectedGenre = selectedGenre === genre ? '' : genre">{{ genre }}</ion-chip></div><section v-if="results.length" class="movie-grid"><MovieCard v-for="movie in results" :key="movie.id" :movie="movie" @select="selectMovie" @favorite="toggleFavorite" /></section><div v-else class="empty-state"><ion-icon :icon="mode === 'favorites' ? heartOutline : bookmarkOutline" /><h2>{{ mode === 'favorites' ? 'No favorites yet' : 'No movies in your watchlist yet' }}</h2><p>Discover movies and add them to your collection.</p></div></main></ion-content><ion-modal :is-open="isAddOpen" @did-dismiss="isAddOpen = false"><ion-header><ion-toolbar><ion-title>Add movie</ion-title><ion-button slot="end" fill="clear" @click="isAddOpen = false">Close</ion-button></ion-toolbar></ion-header><ion-content class="ion-padding"><form class="add-form" @submit.prevent="submitMovie"><ion-input v-model="draft.title" label="Movie title" label-placement="stacked" fill="outline" required /><label class="poster-file-label" for="poster-file">Choose poster image</label><input id="poster-file" class="poster-file" type="file" accept="image/*" @change="handlePosterFile" /><img v-if="draft.poster" class="poster-preview" :src="draft.poster" alt="Poster preview" /><ion-input v-model="draft.genre" label="Genre" label-placement="stacked" fill="outline" required /><ion-input v-model.number="draft.releaseYear" type="number" label="Release year" label-placement="stacked" fill="outline" required /><ion-input v-model.number="draft.rating" type="number" label="Rating (1-10)" label-placement="stacked" fill="outline" min="1" max="10" required /><ion-select v-model="draft.status" label="Watch status" label-placement="stacked" fill="outline"><ion-select-option value="Not Watched">Not Watched</ion-select-option><ion-select-option value="Watched">Watched</ion-select-option></ion-select><ion-textarea v-model="draft.description" label="Synopsis" label-placement="stacked" fill="outline" /><ion-button type="submit" expand="block">Save movie</ion-button></form></ion-content></ion-modal></ion-page>
</template>
<script setup lang="ts">
import { computed, reactive, ref } from 'vue'; import { IonButton, IonChip, IonContent, IonHeader, IonIcon, IonInput, IonModal, IonPage, IonSearchbar, IonSegment, IonSegmentButton, IonSelect, IonSelectOption, IonTextarea, IonTitle, IonToolbar } from '@ionic/vue'; import { bookmarkOutline, heartOutline } from 'ionicons/icons'; import { useRouter } from 'vue-router'; import MovieCard from '../../components/MovieCard.vue'; import { useMovieStore } from '../../stores/movieStore'; import type { Movie } from '../../types/movie'
const props = defineProps<{ mode: 'discover' | 'watchlist' | 'favorites' }>(); const router = useRouter(); const store = useMovieStore(); const { movies, watchlistMovies, favoriteMovies, toggleFavorite, addMovie } = store; const query = ref(''); const filter = ref('all'); const selectedGenre = ref(''); const isAddOpen = ref(false); const draft = reactive({ title: '', genre: 'Drama', releaseYear: new Date().getFullYear(), rating: 7, status: 'Not Watched' as const, poster: '', description: '', director: '', cast: [] as string[], runtime: 120, trailerUrl: '' });
const title = computed(() => props.mode === 'discover' ? 'Discover' : props.mode === 'favorites' ? 'Favorites' : 'My Watchlist'); const genres = computed(() => [...new Set(movies.value.map((movie) => movie.genre))]);
const results = computed(() => { let source = props.mode === 'favorites' ? favoriteMovies.value : props.mode === 'watchlist' ? watchlistMovies.value : movies.value; if (filter.value !== 'all') source = movies.value.filter((movie) => movie.status === filter.value); return source.filter((movie) => (!query.value || `${movie.title} ${movie.genre} ${movie.director}`.toLowerCase().includes(query.value.toLowerCase())) && (!selectedGenre.value || movie.genre === selectedGenre.value)); }); function selectMovie(movie: Movie) { router.push(`/movie/${movie.id}`) }
function handlePosterFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const reader = new FileReader(); reader.addEventListener('load', () => { if (typeof reader.result === 'string') draft.poster = reader.result }); reader.readAsDataURL(file) }
function submitMovie() { if (!draft.title.trim() || !draft.genre.trim()) return; addMovie({ ...draft }); draft.title = ''; draft.poster = ''; draft.description = ''; isAddOpen.value = false }
</script>
<style scoped>.page-shell { max-width: 1100px; margin: auto; padding: 16px; }.segment { margin: 8px 0 20px; }.filter-row { display: flex; overflow-x: auto; gap: 4px; margin: 4px 0 20px; }.movie-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }.empty-state { text-align: center; color: var(--ion-color-medium); padding: 80px 24px; }.empty-state ion-icon { font-size: 52px; color: var(--ion-color-primary); }.empty-state h2 { color: var(--ion-text-color); font-size: 1.25rem; }.add-form { display: grid; gap: 14px; }.poster-preview { width: 96px; aspect-ratio: 2 / 3; object-fit: cover; border-radius: 8px; border: 1px solid var(--surface-border); }@media (min-width: 700px) { .movie-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); } }</style>
